module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [2, 'never', ['upper-case', 'pascal-case', 'start-case']],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'passenger',
        'driver',
        'admin',
        'family',
        'identity',
        'trip',
        'dispatch',
        'tracking',
        'media',
        'payment',
        'panic',
        'notification',
        'audit',
        'rating',
        'share',
        'bff',
        'infra',
        'docs',
        'deps',
        'release',
        'shared',
      ],
    ],
  },
};
