apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: { name: veo, namespace: argocd }
spec:
  description: VEO Platform
  sourceRepos:
    - git@github.com:lucadevv/veo.git
    - https://charts.external-secrets.io # chart oficial de ESO (applications/external-secrets.yaml)
  destinations:
    - { namespace: "veo-*", server: https://kubernetes.default.svc }
    - { namespace: external-secrets, server: https://kubernetes.default.svc } # operador ESO
  clusterResourceWhitelist:
    - { group: "*", kind: "*" }
