source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'

# Ruby 3.4+ sacó kconv/nkf (y 4.1 sacará tsort) de las default gems; CFPropertyList (dep de
# CocoaPods) los necesita → sin esto `bundle exec pod install` revienta con LoadError en
# rbCFPropertyList. El propio mensaje de Ruby dice "add nkf to your Gemfile to fix this error".
gem 'nkf'
gem 'tsort'
