# Module: secrets-manager · variables

variable "env" {
  type = string
}

variable "kms_key_arn" {
  description = "CMK ARN to encrypt the secrets (typically the pii key)"
  type        = string
}

variable "recovery_window_in_days" {
  type    = number
  default = 7
}

variable "generated_secrets" {
  description = <<-EOT
    Secrets whose value Terraform generates randomly (JWT keys, HMAC, panic keys).
    Stored under veo/<env>/<path>. If json_key is set, value is wrapped as JSON.
  EOT
  type = map(object({
    path             = string
    description      = optional(string, "")
    length           = optional(number, 64)
    special          = optional(bool, false)
    override_special = optional(string, "!#$%&*()-_=+")
    json_key         = optional(string, "")
  }))
  default = {}
}

variable "keypair_secrets" {
  description = <<-EOT
    Secrets whose value is an asymmetric keypair generated by Terraform
    (e.g. ES256 for JWT). Stored as JSON {private_key_pem, public_key_pem}.
  EOT
  type = map(object({
    path        = string
    description = optional(string, "")
    algorithm   = optional(string, "ECDSA")
    ecdsa_curve = optional(string, "P256")
  }))
  default = {}
}

variable "managed_secrets" {
  description = "Secrets created empty; value injected out-of-band (operator/CLI)."
  type = map(object({
    path        = string
    description = optional(string, "")
  }))
  default = {}
}

variable "tags" {
  type    = map(string)
  default = {}
}
